### ISSUE TITLE
Use box-shadow on elements as a variable/utility class

### ISSUE THREAD

**Issue by antonieIPR** [pennions/JESS#28]
If I'm correct, all the elements that use a **box-shadow** have this property hard-coded (except for the color):

`box-shadow: 0 1.6px 3.6px 0 rgba(var(--shadow-colour), 0.132),
    0 0.3px 0.9px 0 rgba(var(--shadow-colour), 0.108);` for instance

The x,y values differ for each element (below the `<nav>` element, above the `<footer>` element ) and I am wondering if the following is desirable:

- Apply the same shadow on each element or if needed, make a few shadow styles that share the colour value
- When this variable is available under theming, we can choose if we want to add shadow or not

**Comment by jelmerveen** [comment]
adding them to variables is a good suggestion and nav and footer should be the same.
