### ISSUE TITLE
Z-Index 

### ISSUE THREAD

**Issue by antonieIPR** [pennions/JESS#31]
The footer box-shadow gets hidden behind other elements:
![image](https://github.com/pennions/JESS/assets/64540868/73dde3b0-4c3e-4b99-ba52-eb4f3ca192e2)

Suggestions:
- let the footer also have a `z-index: 1000 !important` like the `nav.main-navigation`
- or is it useful to add utility classes for `z-index`?

**Comment by jelmerveen** [comment]
main-footer should be the same as main-navigation, agreed.

z-index utilities might be something to look in to. needs more research.

**Comment by antonieIPR** [comment]
Note: I added Mapbox GL JS to the site, the map-element was causing the overlap on the footer. Giving the map element a `z-index: 10` solved the issue for now.

**Comment by jelmerveen** [comment]
the navbar only has z-index 1000 because of the sticky class!, will split this issue into its own seperate one for z-index utilities.
