### ISSUE TITLE
border-light is no different from border-black

### ISSUE THREAD

**Issue by antonieIPR** [pennions/JESS#32]
When using `.border-light` I expect to have a border with the light colour applied, like in the other classes. Instead, the class renders a black border.

**Comment by antonieIPR** [comment]
Current workaround for this issue:

```
.border-custom{
    border-color: var(--light);
}
```

**Comment by jelmerveen** [comment]
After looking into the code, you are absolutely correct.

This is a bug introduced by the refactoring, it still points to the hr colour which does not exist,

```
border-color: var(--hr-color) !important;
}```
